language: ruby
rvm:
- 2.3.1
before_script:
- npm install -g bower
- bower install
- chmod +x ./scripts/cibuild.sh
script: "./scripts/cibuild.sh"
after_success:
- chmod +x ./scripts/deploy.sh
- "./scripts/deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: me@marcanuy.com
  - ENCRYPTION_LABEL: "8377852856fe"
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_8377852856fe_key -iv $encrypted_8377852856fe_iv
  -in deploy_key.enc -out deploy_key -d
