language: ruby
rvm:
- 2.3.1
before_script:
- npm install -g bower
- bower install
- chmod +x ./scripts/cibuild.sh
script: bash ./scripts/cibuild.sh
after_success: bash ./deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: me@marcanuy.com
  - ENCRYPTION_LABEL: 9f3844c952a5
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_9f3844c952a5_key -iv $encrypted_9f3844c952a5_iv -in deploy_key.enc -out deploy_key -d
