# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple IT 🤘 Rocks
email: me@marcanuy.com
description: > # this means to ignore newlines until "baseurl:"
  Clutter-free software concepts.
  Written on the go.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simpleit.rocks" # the base hostname & protocol for your site

author: marcanuy #Twitter handle
docs_dir: "docs"
  
permalink: /:title/
#permalink: /:categories/:title/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

disqus_id: "simpleitrocks"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  
#jekyll-seo-plugin 
#twitter:
#  username: benbalter #The site's Twitter handle.
#logo: "/assets/your-company-logo.png" #URL to a site-wide logo
facebook:
  app_id: 1822851531277021
#  publisher: 1234
#  admins: 1234
#social: # For specifying social profiles. The following properties are available:
#  name: "" # If the user or organization name differs from the site's name
#  links: # An array of links to social media profiles.


########################################################################################################
# The SEO tag will respect the following YAML front matter if included in a post, page, or document:   #
#     title - The title of the post, page, or document                                                 #
#     description - A short description of the page's content                                          #
#     image - URL to an image associated with the post, page, or document (e.g., /assets/page-pic.jpg) #
#     author - Page-, post-, or document-specific author information (see below)                       #
########################################################################################################

