# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple IT 🤘 Rocks
email: me@marcanuy.com
description: > # this means to ignore newlines until "baseurl:"
  Clutter-free software concepts.
  Written on the go.
baseurl: "/it-notes" # the subpath of your site, e.g. /blog
url: "http://simpleit.rocks" # the base hostname & protocol for your site
twitter_username: marcanuy
#github_username:  marcanuy
docs_dir: "software"
  
permalink: /:title/
#permalink: /:categories/:title/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "practice"
      type: "posts"
    values:
      layout: "post"

